name: Chemdah Release

on:
  push:
    branches: [ "rebirth" ]
  pull_request:
    branches: [ "rebirth" ]
  workflow_dispatch: # 允许手动触发

jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build
        id: build_1
        run: ./gradlew build

      - name: build (retry 1)
        id: build_2
        if: steps.build_1.outcome == 'failure'
        run: ./gradlew build

      - name: build (retry 2)
        id: build_3
        if: steps.build_2.outcome == 'failure'
        run: ./gradlew build

      - name: build (retry 3)
        id: build_4
        if: steps.build_3.outcome == 'failure'
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Chemdah Release
          path: build/libs/*.jar
